/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "var(--color-primary, #154212)",
        background: "var(--color-background, #f8f9fa)",
        "on-secondary": "var(--color-on-secondary, #ffffff)",
        "tertiary-fixed": "var(--color-tertiary-fixed, #ffd9e4)",
        "on-primary": "var(--color-on-primary, #ffffff)",
        "secondary-fixed": "var(--color-secondary-fixed, #ffdfa0)",
        "primary-container": "var(--color-primary-container, #2d5a27)",
        secondary: "var(--color-secondary, #795900)",
        "surface-container-highest": "var(--color-surface-container-highest, #e1e3e4)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant, #23501e)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim, #ffb0cc)",
        "surface-container-low": "var(--color-surface-container-low, #f3f4f5)",
        tertiary: "var(--color-tertiary, #60233e)",
        "on-surface": "var(--color-on-surface, #191c1d)",
        "on-tertiary-container": "var(--color-on-tertiary-container, #ffaac8)",
        "surface-container": "var(--color-surface-container, #edeeef)",
        surface: "var(--color-surface, #f8f9fa)",
        "surface-container-lowest": "var(--color-surface-container-lowest, #ffffff)",
        "on-primary-fixed": "var(--color-on-primary-fixed, #002201)",
        "surface-tint": "var(--color-surface-tint, #3b6934)",
        "surface-variant": "var(--color-surface-variant, #e1e3e4)",
        "on-error": "var(--color-on-error, #ffffff)",
        "on-surface-variant": "var(--color-on-surface-variant, #42493e)",
        "primary-fixed": "var(--color-primary-fixed, #bcf0ae)",
        "on-error-container": "var(--color-on-error-container, #93000a)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed, #3b0520)",
        "on-tertiary": "var(--color-on-tertiary, #ffffff)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim, #fbbc00)",
        "tertiary-container": "var(--color-tertiary-container, #7c3a55)",
        outline: "var(--color-outline, #72796e)",
        "inverse-on-surface": "var(--color-inverse-on-surface, #f0f1f2)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant, #5c4300)",
        "on-background": "var(--color-on-background, #191c1d)",
        "inverse-primary": "var(--color-inverse-primary, #a1d494)",
        "error-container": "var(--color-error-container, #ffdad6)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim, #a1d494)",
        error: "var(--color-error, #ba1a1a)",
        "surface-bright": "var(--color-surface-bright, #f8f9fa)",
        "surface-dim": "var(--color-surface-dim, #d9dadb)",
        "surface-container-high": "var(--color-surface-container-high, #e7e8e9)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant, #71314c)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed, #261a00)",
        "on-primary-container": "var(--color-on-primary-container, #9dd090)",
        "secondary-container": "var(--color-secondary-container, #ffbf00)",
        "on-secondary-container": "var(--color-on-secondary-container, #6d5000)",
        "outline-variant": "var(--color-outline-variant, #c2c9bb)",
        "inverse-surface": "var(--color-inverse-surface, #2e3132)",
        "border-subtle": "#1e293b",
        "trend-up": "#10b981",
        "trend-down": "#ef4444",
        "trend-warn": "#f59e0b"
      },
      borderRadius: {
        card: "16px",
      },
      spacing: {
        "stack-md": "1rem",
        unit: "8px",
        "touch-target-min": "56px",
        "container-margin": "1.5rem",
        "stack-sm": "0.5rem",
        gutter: "1rem",
        "stack-lg": "2rem",
        "nav-bar": "64px",
        "margin-desktop": "24px",
        "margin-mobile": "16px",
        "panel-gap": "1px"
      },
      fontFamily: {
        "headline-sm": ["Inter", "Space Grotesk"],
        "headline-md": ["Inter", "Space Grotesk"],
        "body-lg": ["Inter", "Geist"],
        "body-md": ["Inter", "Geist"],
        "headline-lg": ["Inter", "Space Grotesk"],
        "label-sm": ["Inter"],
        "label-lg": ["Inter"],
        "mono-data": ["Geist"],
        "display-lg": ["Space Grotesk"],
        "label-caps": ["Geist"]
      }
    },
  },
  plugins: [],
}
